// Date: 17/05/2014 19:06:09
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.vivalux.cyb.client.model;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEyeImplant extends ModelBiped {

	ModelRenderer EyeOverlay1;
	ModelRenderer EyeSide2;
	ModelRenderer EyeOverlay2;
	ModelRenderer EyeSide1;
	ModelRenderer EyeSide3;
	ModelRenderer EyeSide4;
	ModelRenderer EyeSide5;

	public ModelEyeImplant() {
		textureWidth = 64;
		textureHeight = 64;
		int yOffset = 1;

		EyeOverlay1 = new ModelRenderer(this, 0, 3);
		EyeOverlay1.addBox(-3F, -6F + yOffset, -5F, 2, 2, 1);
		EyeOverlay1.setRotationPoint(0F, 0F, 0F);
		EyeOverlay1.setTextureSize(64, 64);
		EyeOverlay1.mirror = true;
		setRotation(EyeOverlay1, 0F, 0F, 0F);

		EyeSide2 = new ModelRenderer(this, 0, 7);
		EyeSide2.addBox(-5F, -5.5F + yOffset, -5F, 2, 1, 1);
		EyeSide2.setRotationPoint(0F, 0F, 0F);
		EyeSide2.setTextureSize(64, 64);
		EyeSide2.mirror = true;
		setRotation(EyeSide2, 0F, 0F, 0F);

		EyeOverlay2 = new ModelRenderer(this, 0, 0);
		EyeOverlay2.addBox(-2.5F, -5.5F + yOffset, -6F, 1, 1, 1);
		EyeOverlay2.setRotationPoint(0F, 0F, 0F);
		EyeOverlay2.setTextureSize(64, 64);
		EyeOverlay2.mirror = true;
		setRotation(EyeOverlay2, 0F, 0F, 0F);

		EyeSide1 = new ModelRenderer(this, 7, 0);
		EyeSide1.addBox(-5F, -5.5F + yOffset, -4F, 1, 1, 9);
		EyeSide1.setRotationPoint(0F, 0F, 0F);
		EyeSide1.setTextureSize(64, 64);
		EyeSide1.mirror = true;
		setRotation(EyeSide1, 0F, 0F, 0F);

		EyeSide3 = new ModelRenderer(this, 0, 10);
		EyeSide3.addBox(-5F, -6F + yOffset, 0F, 1, 2, 1);
		EyeSide3.setRotationPoint(0F, 0F, 0F);
		EyeSide3.setTextureSize(64, 64);
		EyeSide3.mirror = true;
		setRotation(EyeSide3, 0F, 0F, 0F);

		EyeSide4 = new ModelRenderer(this, 0, 14);
		EyeSide4.addBox(-4F, -5.5F + yOffset, 4F, 4, 1, 1);
		EyeSide4.setRotationPoint(0F, 0F, 0F);
		EyeSide4.setTextureSize(64, 64);
		EyeSide4.mirror = true;
		setRotation(EyeSide4, 0F, 0F, 0F);

		EyeSide5 = new ModelRenderer(this, 0, 17);
		EyeSide5.addBox(-1F, -6F + yOffset, 4F, 1, 2, 1);
		EyeSide5.setRotationPoint(0F, 0F, 0F);
		EyeSide5.setTextureSize(64, 64);
		EyeSide5.mirror = true;
		setRotation(EyeSide5, 0F, 0F, 0F);

		this.bipedHead.addChild(EyeOverlay1);
		this.bipedHead.addChild(EyeOverlay2);
		this.bipedHead.addChild(EyeSide1);
		this.bipedHead.addChild(EyeSide2);
		this.bipedHead.addChild(EyeSide3);
		this.bipedHead.addChild(EyeSide4);
		this.bipedHead.addChild(EyeSide5);

	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		/*
		 * EyeOverlay1.render(f5); EyeSide2.render(f5); EyeOverlay2.render(f5);
		 * EyeSide1.render(f5); EyeSide3.render(f5); EyeSide4.render(f5);
		 * EyeSide5.render(f5);
		 */
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
	}

}
